language: cpp

os:
  - linux
  - osx

dist: trusty
sudo: required

before_install:
  - if [ ${TRAVIS_OS_NAME} = "linux" ]; then sudo apt-get -qq update; fi
  - if [ ${TRAVIS_OS_NAME} = "linux" ]; then sudo apt-get install -y libzmq3-dev libzmqpp-dev; fi
  - if [ ${TRAVIS_OS_NAME} = "linux" ]; then sudo apt-get install -y qt5-default libqt5webkit5-dev libqt5printsupport5; fi
  - if [ ${TRAVIS_OS_NAME} = "linux" ]; then sudo apt-get install -y libboost-date-time-dev libjsoncpp-dev openssl; fi
  - if [ ${TRAVIS_OS_NAME} = "osx" ]; then brew update && brew tap caskroom/cask && brew install brew-cask && brew cask install java && brew install ant; fi
  
before_script:
  - mkdir cmake_build && cd cmake_build
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then cmake ENABLE_CYACAS_KERNEL=Off .. ; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then unset CXX; unset CC; cmake -G Xcode .. ; fi

script:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then make; fi
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then make test ; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then xcodebuild -project yacas.xcodeproj -target ALL_BUILD; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then xcodebuild -project yacas.xcodeproj -target RUN_TESTS; fi
  - cd .. && ant && ant test

branches:
  except:
    - gh_pages
    - vendor
    - bignum_experiments
    - coverity_scan
